name: Deploy app

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
      - name: Deploy
        run: |
          # sudo snap install doctl
          # doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          # doctl serverless connect maker
          doctl serverless deploy . --remote-build